(define-library (kaappi bdd reporter)
  (import (scheme base) (scheme write))
  (export report-group-begin report-group-end
          report-spec-pass report-spec-fail report-spec-pending
          report-summary report-failure-detail
          %pass-count %fail-count %pending-count %failures)
  (begin
    (define %pass-count 0)
    (define %fail-count 0)
    (define %pending-count 0)
    (define %failures '())
    (define %depth 0)

    (define (indent)
      (let loop ((i 0))
        (when (< i %depth)
          (display "  ")
          (loop (+ i 1)))))

    (define (report-group-begin desc)
      (indent)
      (display desc)
      (newline)
      (set! %depth (+ %depth 1)))

    (define (report-group-end)
      (set! %depth (- %depth 1)))

    (define (report-spec-pass desc)
      (set! %pass-count (+ %pass-count 1))
      (indent)
      (display desc)
      (display "  ok")
      (newline))

    (define (report-spec-fail desc message)
      (set! %fail-count (+ %fail-count 1))
      (set! %failures (cons (cons desc message) %failures))
      (indent)
      (display desc)
      (display "  FAIL")
      (newline))

    (define (report-spec-pending desc)
      (set! %pending-count (+ %pending-count 1))
      (indent)
      (display desc)
      (display "  (pending)")
      (newline))

    (define (report-failure-detail)
      (when (pair? %failures)
        (newline)
        (display "Failures:")
        (newline)
        (let loop ((fs (reverse %failures)) (i 1))
          (when (pair? fs)
            (newline)
            (display "  ")
            (display i)
            (display ") ")
            (display (caar fs))
            (newline)
            (display "     ")
            (display (cdar fs))
            (newline)
            (loop (cdr fs) (+ i 1))))))

    (define (report-summary)
      (report-failure-detail)
      (newline)
      (let ((total (+ %pass-count %fail-count %pending-count)))
        (display total)
        (display " example")
        (when (not (= total 1)) (display "s"))
        (display ", ")
        (display %fail-count)
        (display " failure")
        (when (not (= %fail-count 1)) (display "s"))
        (when (> %pending-count 0)
          (display ", ")
          (display %pending-count)
          (display " pending"))
        (newline)))))
